version: '3.1'

services:

  minio:
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
      - ./keys:/keys
    environment:
      MINIO_ROOT_USER: minIO
      MINIO_ROOT_PASSWORD: <PASSWORD>
      MINIO_ROOT_USER_FILE: /keys/access_key
      MINIO_ROOT_PASSWORD_FILE: /keys/secret_key
    command: server --console-address ":9001" /data
  